# Generated by Django 3.1.7 on 2021-03-28 04:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 3, 28, 0, 15, 12, 66840))),
                ('cals_burned', models.PositiveSmallIntegerField()),
                ('duration_hours', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RunningEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hoosactive.entry')),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_speed', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('hoosactive.entry',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('age', models.PositiveSmallIntegerField()),
                ('height_feet', models.PositiveSmallIntegerField()),
                ('height_inches', models.PositiveSmallIntegerField()),
                ('weight_lbs', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bio_text', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('show_stats', models.BooleanField(default=True)),
                ('exercises', models.ManyToManyField(to='hoosactive.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoosactive.exercise'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
