# Generated by Django 3.1.7 on 2021-03-28 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushUpsEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hoosactive.entry')),
                ('reps', models.PositiveSmallIntegerField()),
            ],
            bases=('hoosactive.entry',),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 1, 45, 17, 212821)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
