# Generated by Django 3.1.7 on 2021-03-28 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0004_auto_20210328_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 3, 7, 2, 236338)),
        ),
    ]
