# Generated by Django 3.1.7 on 2021-03-28 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0007_auto_20210328_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 14, 6, 40, 457413)),
        ),
    ]
