# Generated by Django 3.1.7 on 2021-03-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0009_auto_20210329_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 4, 13, 20, 206784)),
        ),
    ]
