# Generated by Django 3.1.5 on 2021-04-11 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0011_auto_20210411_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_log',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 3, 59, 4, 437701)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 3, 59, 4, 438464)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 3, 59, 4, 438803)),
        ),
    ]
