# Generated by Django 3.1.6 on 2021-04-06 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0011_auto_20210406_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 4, 5, 58, 344128)),
        ),
    ]
