# Generated by Django 3.1.6 on 2021-04-06 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0012_auto_20210406_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 14, 25, 55, 944993)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.TextField(),
        ),
    ]
