# Generated by Django 3.1.5 on 2021-04-11 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0013_auto_20210411_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
