# Generated by Django 3.1.6 on 2021-04-09 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0014_auto_20210406_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 21, 28, 42, 31615)),
        ),
    ]
