# Generated by Django 3.1.5 on 2021-04-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0015_auto_20210408_2128'),
        ('hoosactive', '0014_auto_20210411_0444'),
    ]

    operations = [
    ]
