# Generated by Django 3.1.5 on 2021-04-11 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoosactive', '0016_merge_20210411_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friends_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
