# Generated by Django 3.1.5 on 2021-04-16 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoosactive', '0018_auto_20210411_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(related_name='friend_requests_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_text',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
