# Generated by Django 3.1.5 on 2021-04-17 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoosactive', '0019_auto_20210416_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
