    # Generated by Django 3.1.6 on 2021-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0019_auto_20210416_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to=''),
        ),
    ]
