# Generated by Django 3.1.5 on 2021-04-17 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoosactive', '0020_auto_20210417_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='hoosactive.Exercise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
