# Generated by Django 3.1.6 on 2021-04-17 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoosactive', '0020_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='hoosactive.Exercise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
