# Generated by Django 3.1.6 on 2021-04-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0021_auto_20210417_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
