# Generated by Django 3.1.5 on 2021-04-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0021_auto_20210417_1554'),
        ('hoosactive', '0023_auto_20210417_2200'),
    ]

    operations = [
    ]
