# Generated by Django 3.1.6 on 2021-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0024_merge_20210418_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio_text',
            field=models.CharField(max_length=150),
        ),
    ]
