# Generated by Django 3.1.6 on 2021-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0025_auto_20210418_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio_text',
            field=models.TextField(max_length=150),
        ),
    ]
