# Generated by Django 3.1.6 on 2021-04-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0026_auto_20210418_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_stats',
            field=models.BooleanField(default=False),
        ),
    ]
