# Generated by Django 3.1.6 on 2021-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0028_auto_20210419_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
    ]
