# Generated by Django 3.1.5 on 2021-04-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0033_auto_20210423_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reset_password',
        ),
    ]
