# Generated by Django 3.1.5 on 2021-05-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoosactive', '0034_auto_20210423_1944'),
        ('hoosactive', '0032_auto_20210428_1429'),
    ]

    operations = [
    ]
